export const studentTherapistData = {
  personalDetails: {
    age: 24,
    email: "rishabmehta@gmail.com",
    name: "Rishab Mehta",
    password: "RishabMehta",
    phone_no: "9819021848",
    sex: "M",
  },
  professionalDetails: {
    availability: [
      "Mon 09:00",
      "Mon 10:00",
      "Mon 11:00",
      "Mon 12:00",
      "Thu 09:00",
      "Thu 10:00",
      "Thu 11:00",
      "Thu 12:00",
    ],
    experience_years: 2,
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    qualifications: ["Vocal Therapy", "Speech Therapy", "Autism Support"],
    specialization: ["M.Sc. Speech Pathology", "B.Sc. Audiology"],
    spoken_languages: ["English", "Hindi", "Marathi", "Gujarati"],
    client_coursework: ["Autism 1 year", "Vocal 2 years"],
  },
  patients: [
    {
      id: 1,
      name: "Ananya Sharma",
      age: 10,
      condition: "Speech Therapy",
      startDate: "2024-01-15",
      progress: 70,
      nextAppointment: "2024-03-20",
      status: "Active",
    },
    {
      id: 2,
      name: "Rohan Desai",
      age: 7,
      condition: "Autism Support",
      startDate: "2023-11-10",
      progress: 55,
      nextAppointment: "2024-03-22",
      status: "Active",
    },
    {
      id: 3,
      name: "Pooja Nair",
      age: 14,
      condition: "Vocal Training",
      startDate: "2023-12-01",
      progress: 85,
      nextAppointment: "2024-03-25",
      status: "Completing",
    },
  ],
  feedback: [
    {
      id: 1,
      date: "2024-03-15",
      supervisor: "Dr. Suresh Gupta",
      rating: 4.6,
      comments:
        "Exceptional progress in handling speech therapy cases. Innovative techniques and strong patient rapport.",
      areas: ["Patient Engagement", "Treatment Planning"],
    },
    {
      id: 2,
      date: "2024-02-28",
      supervisor: "Dr. Anjali Kapoor",
      rating: 4.2,
      comments:
        "Great efforts in autism support cases. Can improve in case documentation accuracy.",
      areas: ["Clinical Skills", "Case Documentation"],
    },
    {
      id: 3,
      date: "2024-02-15",
      supervisor: "Dr. Vinay Kulkarni",
      rating: 4.9,
      comments:
        "Outstanding techniques in vocal therapy sessions. Shows measurable improvement in students’ outcomes.",
      areas: ["Teaching Strategies", "Outcome Tracking"],
    },
  ],
};
