const allPatients = [
  {
    id: 1,
    name: "Rajesh Sharma",
    age: 45,
    admissionDate: "2024-03-15",
    diagnosis: "Post-operative rehabilitation",
    therapists: [
      { id: 1, name: "Ananya Sharma", role: "Primary Therapist" },
      { id: 2, name: "Rohan Deshmukh", role: "Assistant Therapist" },
    ],
    timeline: [
      { date: "2024-03-15", event: "Admitted to hospital" },
      { date: "2024-03-20", event: "Started physical therapy" },
      { date: "2024-04-01", event: "Completed first phase" },
    ],
    latestReport: {
      id: "R123",
      date: "2024-04-05",
      title: "Monthly Progress Report",
    },
  },
  {
    id: 2,
    name: "Priya Malhotra",
    age: 28,
    admissionDate: "2024-02-20",
    diagnosis: "Anxiety and Depression",
    therapists: [
      { id: 3, name: "Ishita Patel", role: "Primary Therapist" },
      { id: 4, name: "Vivaan Singh", role: "Counselor" },
      { id: 5, name: "Karan Mehta", role: "Group Therapist" },
    ],
    timeline: [
      { date: "2024-02-20", event: "Initial consultation" },
      { date: "2024-02-25", event: "Started individual therapy" },
      { date: "2024-03-10", event: "Joined group therapy sessions" },
      { date: "2024-03-30", event: "Medication adjustment" },
    ],
    latestReport: {
      id: "R124",
      date: "2024-04-01",
      title: "Therapy Progress Evaluation",
    },
  },
  {
    id: 3,
    name: "Arjun Kapoor",
    age: 62,
    admissionDate: "2024-01-10",
    diagnosis: "Stroke Recovery",
    therapists: [
      { id: 6, name: "Sanya Gupta", role: "Physical Therapist" },
      { id: 7, name: "Sameer Gupta", role: "Speech Therapist" },
      { id: 8, name: "Shanaya Sharma", role: "Occupational Therapist" },
    ],
    timeline: [
      { date: "2024-01-10", event: "Admitted post-stroke" },
      { date: "2024-01-15", event: "Started physical therapy" },
      { date: "2024-02-01", event: "Began speech therapy" },
      { date: "2024-02-15", event: "Started occupational therapy" },
      { date: "2024-03-20", event: "Significant improvement in mobility" },
    ],
    latestReport: {
      id: "R125",
      date: "2024-04-03",
      title: "Rehabilitation Progress Report",
    },
  },
  {
    id: 4,
    name: "Aastha Shukla",
    age: 16,
    admissionDate: "2024-03-01",
    diagnosis: "Eating Disorder",
    therapists: [
      { id: 9, name: "Kiran Mehra", role: "Primary Therapist" },
      { id: 10, name: "Parth Gala", role: "Nutritionist" },
      { id: 11, name: "Aarav Patel", role: "Family Therapist" },
    ],
    timeline: [
      { date: "2024-03-01", event: "Initial assessment" },
      { date: "2024-03-05", event: "Started nutritional counseling" },
      { date: "2024-03-15", event: "Family therapy session" },
      { date: "2024-03-25", event: "Group support session" },
    ],
    latestReport: {
      id: "R126",
      date: "2024-04-04",
      title: "Treatment Progress Update",
    },
  },
  {
    id: 5,
    name: "Vikram Singhania",
    age: 35,
    admissionDate: "2024-02-10",
    diagnosis: "Substance Abuse Recovery",
    therapists: [
      { id: 12, name: "Kabir Malhotra", role: "Addiction Specialist" },
      { id: 13, name: "Riya Verma", role: "Group Counselor" },
      { id: 14, name: "Dev Kumar", role: "Support Counselor" },
    ],
    timeline: [
      { date: "2024-02-10", event: "Began rehabilitation program" },
      { date: "2024-02-15", event: "Started individual counseling" },
      { date: "2024-03-01", event: "Joined support group" },
      { date: "2024-03-20", event: "Completed first month sober" },
      { date: "2024-04-01", event: "Family reconciliation session" },
    ],
    latestReport: {
      id: "R127",
      date: "2024-04-05",
      title: "Recovery Progress Report",
    },
  },
  {
    id: 6,
    name: "Meera Desai",
    age: 52,
    admissionDate: "2024-01-25",
    diagnosis: "Chronic Pain Management",
    therapists: [
      { id: 15, name: "Aryan Khanna", role: "Pain Management Specialist" },
      { id: 16, name: "Nisha Thakur", role: "Physical Therapist" },
      { id: 17, name: "Aditya Joshi", role: "Psychological Counselor" },
    ],
    timeline: [
      { date: "2024-01-25", event: "Initial pain assessment" },
      { date: "2024-02-01", event: "Started pain management program" },
      { date: "2024-02-15", event: "Physical therapy integration" },
      { date: "2024-03-01", event: "Medication adjustment" },
      { date: "2024-03-15", event: "Progress evaluation" },
      { date: "2024-04-01", event: "Treatment plan modification" },
    ],
    latestReport: {
      id: "R128",
      date: "2024-04-06",
      title: "Pain Management Update",
    },
  },
  {
    id: 7,
    name: "Rahul Mehta",
    age: 73,
    admissionDate: "2024-02-05",
    diagnosis: "Alzheimer's Care",
    therapists: [
      { id: 18, name: "Neha Sinha", role: "Geriatric Specialist" },
      { id: 19, name: "Alia Kapoor", role: "Memory Care Therapist" },
      { id: 20, name: "Anjali Reddy", role: "Occupational Therapist" },
    ],
    timeline: [
      { date: "2024-02-05", event: "Admission to memory care unit" },
      { date: "2024-02-10", event: "Cognitive assessment" },
      { date: "2024-02-20", event: "Started memory exercises" },
      { date: "2024-03-05", event: "Family care planning session" },
      { date: "2024-03-25", event: "Activity program adjustment" },
    ],
    latestReport: {
      id: "R129",
      date: "2024-04-02",
      title: "Cognitive Care Assessment",
    },
  },
  {
    id: 8,
    name: "Pooja Iyer",
    age: 31,
    admissionDate: "2024-03-10",
    diagnosis: "Postpartum Depression",
    therapists: [
      { id: 21, name: "Kavita Menon", role: "Primary Therapist" },
      { id: 22, name: "Rohit Shah", role: "Family Counselor" },
      { id: 23, name: "Priyanka Chopra", role: "Support Specialist" },
    ],
    timeline: [
      { date: "2024-03-10", event: "Initial screening" },
      { date: "2024-03-15", event: "Started therapy sessions" },
      { date: "2024-03-25", event: "Family support session" },
      { date: "2024-04-01", event: "Treatment plan review" },
    ],
    latestReport: {
      id: "R130",
      date: "2024-04-05",
      title: "Therapeutic Progress Report",
    },
  },
];

export default allPatients;
