export const initialFormData = {
  "pre-therapy": {
    name: "",
    age: "",
    sex: "",
    date_of_assignment: "",
    provisional_diagnosis: "",
    findings: {
      opme: "",
      reception: "",
      expression: "",
      pragmatics: "",
      attention: "",
      auditory_skill: "",
      play_behavior: "",
      general_behavior: "",
      formal_testing: "",
      clinical_impression: "",
      additional_notes: "",
    },
  },
  session: {
    report_name: "",
    report_type: "",
    report_status: "",
    session_number: "",
    date_of_session: "",
    start_time: "",
    end_time: "",
    progress: "",
    goals: "",
    machines_used: [],
    notes: "",
    results: "",
    external_test: "",
    next_session_date: "",
    next_session_timings: "",
    next_session_therapist: "",
    to_do_before_next_session: "",
    progress_next_session: "",
    goals_next_session: "",
  },
  "therapy-plan": {
    treatment_approach: "",
    planned_interventions: "",
    expected_outcomes: "",
    frequency_of_sessions: "",
    estimated_duration: "",
  },
  "progress-report": {
    case_no: "",
    session_no: "",
    name: "",
    status: "",
    history: "",
    diagnosis: "",
    treatment_plan: "",
    progress: "",
    medicine: "",
    equipments: "",
    findings: "",
  },
};
