export const roomData = [
  {
    floorNo: 1,
    rooms: [
      {
        roomNo: 101,
        roomName: "Room-101",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-101.mp4",
      },
      {
        roomNo: 102,
        roomName: "Room-102",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-102.mp4",
      },
      {
        roomNo: 103,
        roomName: "Room-103",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-103.mp4",
      },
      {
        roomNo: 104,
        roomName: "Room-104",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-104.mp4",
      },
      {
        roomNo: 105,
        roomName: "Room-105",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-105.mp4",
      },
      {
        roomNo: 106,
        roomName: "Room-106",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-106.mp4",
      },
      {
        roomNo: 107,
        roomName: "Room-107",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-107.mp4",
      },
      {
        roomNo: 108,
        roomName: "Room-108",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-108.mp4",
      },
      {
        roomNo: 109,
        roomName: "Room-109",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-109.mp4",
      },
      {
        roomNo: 110,
        roomName: "Room-110",
        floorNo: 1,
        therapyTypes: ["Speech Therapy", "Articulation Therapy"],
        videoRoute: "/videos/room-110.mp4",
      },
    ],
  },
  {
    floorNo: 2,
    rooms: [
      {
        roomNo: 201,
        roomName: "Room-201",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-201.mp4",
      },
      {
        roomNo: 202,
        roomName: "Room-202",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-202.mp4",
      },
      {
        roomNo: 203,
        roomName: "Room-203",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-203.mp4",
      },
      {
        roomNo: 204,
        roomName: "Room-204",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-204.mp4",
      },
      {
        roomNo: 205,
        roomName: "Room-205",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-205.mp4",
      },
      {
        roomNo: 206,
        roomName: "Room-206",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-206.mp4",
      },
      {
        roomNo: 207,
        roomName: "Room-207",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-207.mp4",
      },
      {
        roomNo: 208,
        roomName: "Room-208",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-208.mp4",
      },
      {
        roomNo: 209,
        roomName: "Room-209",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-209.mp4",
      },
      {
        roomNo: 210,
        roomName: "Room-210",
        floorNo: 2,
        therapyTypes: ["Language Therapy", "Fluency Therapy"],
        videoRoute: "/videos/room-210.mp4",
      },
    ],
  },
  {
    floorNo: 3,
    rooms: [
      {
        roomNo: 301,
        roomName: "Room-301",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-301.mp4",
      },
      {
        roomNo: 302,
        roomName: "Room-302",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-302.mp4",
      },
      {
        roomNo: 303,
        roomName: "Room-303",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-303.mp4",
      },
      {
        roomNo: 304,
        roomName: "Room-304",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-304.mp4",
      },
      {
        roomNo: 305,
        roomName: "Room-305",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-305.mp4",
      },
      {
        roomNo: 306,
        roomName: "Room-306",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-306.mp4",
      },
      {
        roomNo: 307,
        roomName: "Room-307",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-307.mp4",
      },
      {
        roomNo: 308,
        roomName: "Room-308",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-308.mp4",
      },
      {
        roomNo: 309,
        roomName: "Room-309",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-309.mp4",
      },
      {
        roomNo: 310,
        roomName: "Room-310",
        floorNo: 3,
        therapyTypes: ["Cognitive Communication Therapy", "Voice Therapy"],
        videoRoute: "/videos/room-310.mp4",
      },
    ],
  },
  {
    floorNo: 4,
    rooms: [
      {
        roomNo: 401,
        roomName: "Room-401",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-401.mp4",
      },
      {
        roomNo: 402,
        roomName: "Room-402",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-402.mp4",
      },
      {
        roomNo: 403,
        roomName: "Room-403",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-403.mp4",
      },
      {
        roomNo: 404,
        roomName: "Room-404",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-404.mp4",
      },
      {
        roomNo: 405,
        roomName: "Room-405",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-405.mp4",
      },
      {
        roomNo: 406,
        roomName: "Room-406",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-406.mp4",
      },
      {
        roomNo: 407,
        roomName: "Room-407",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-407.mp4",
      },
      {
        roomNo: 408,
        roomName: "Room-408",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-408.mp4",
      },
      {
        roomNo: 409,
        roomName: "Room-409",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-409.mp4",
      },
      {
        roomNo: 410,
        roomName: "Room-410",
        floorNo: 4,
        therapyTypes: ["Pragmatic Language Therapy", "AAC Therapy"],
        videoRoute: "/videos/room-410.mp4",
      },
    ],
  },
];
